### PR TITLE
Local datasets scaling graph

### PR DESCRIPTION
**Pull request by ploh**
WIP

### CODE REVIEW

**Comment by ploh** [comment]
@antw @ChaelKruip I found a bug in my current scaling implementation:
I scaled the `nl` dataset (down by a factor of 100) with `rake scale` in etsource. Then I created a scenario each and checked all demands by executing
```ruby
Hash[@scope.graph.converters.map{|c| [c.key, c.demand] }]
```
in the sandbox (for each scenario).

The following nodes have grossly wrong demands:
```
:energy_regasification_lng
19812576517.766537 <- actual scaled
198125765.17766544 <- expected scaled, i.e. nl value / 100

:energy_distribution_lng
19814185158.99843
199734405.97766545

:energy_import_lng
19814185158.99843
199734405.97766545

:energy_export_network_gas
25491867884.221226
11712784455.961737
```

This looks to me like `energy_regasification_lng` has for some reason got the exact original nl demand. And the others are probably subsequent errors caused by this.

What I cannot figure out: Why does this wrong demand of `energy_regasification_lng` come from?

cc @grdw

**Comment by ChaelKruip** [comment]
> And the others are probably subsequent errors caused by this.

It looks that way indeed!

> Why does this wrong demand of `energy_regasification_lng` come from?

Perhaps stating the blatantly obvious but: it looks like it is not scaled at all... Are you sure you included it in the nodes that need scaling and spelled it correctly and such? Is there a check you can do in the code to see if this particular node is 'touched' by your rake task?

**Comment by ploh** [comment]
When comparing the Co2 emissions with
```TXT_TABLE(G(final_demand_group),primary_co2_emission, key)```

I get the following errors:

```
:agriculture_final_demand_electricity
24554155.662768193 <- actual scaled
17465733.684546404 <- expected scaled, i.e. nl / 100

:agriculture_final_demand_network_gas
28255190.5509747
20098334.479394592

:agriculture_final_demand_steam_hot_water
41724727.55335945
29879508.725045703

:buildings_final_demand_electricity
130302280.845806
112697009.11983529

:buildings_final_demand_network_gas
160093288.42069897
113876721.2622603

:buildings_final_demand_steam_hot_water
23253461.942541543
17523500.09027507

:energy_heat_network_unused_steam_hot_water
27448947.573849943
20685162.34171294

:energy_power_sector_own_use_electricity
16002799.077678623
13904143.10843557

:households_final_demand_electricity
96744797.57538232
83673511.03816389

:households_final_demand_network_gas
260392836.77579457
185221271.82673648

:households_final_demand_steam_hot_water
12601485.698167212
9496312.26159256

:industry_final_demand_electricity
149825663.06247193
126836137.10907745

:industry_final_demand_for_other_ict_electricity
10498365.734476652
9079921.0208895

:industry_final_demand_network_gas
212467862.94075334
151131529.8971898

:industry_final_demand_steam_hot_water
64051323.43997973
48385025.33267839

:transport_final_demand_compressed_network_gas
601550.1002347288
436470.70081096975

:transport_final_demand_electricity
6824119.171849319
5902105.592877647
```

**Comment by ploh** [comment]
> Perhaps stating the blatantly obvious but: it looks like it is not scaled at all... Are you sure you included it in the nodes that need scaling and spelled it correctly and such? Is there a check you can do in the code to see if this particular node is 'touched' by your rake task?

Unfortunately, it does not work like this: The demand of _every_ node is scaled. But this is done prior to running refinery. I checked in the exported `graph.yml` and this node does not have a demand set there. The closest node containing "lng" in its name was `transport_final_demand_for_road_lng` and that has its demand correctly scaled.
So the node itself is not "touched" by my rake task and it should not have to be. I scale all the area attributes (i.e. those inside country.ad), all the node attributes (only those existing pre-Refinery of course and except shares) and the time curves.

**Comment by ploh** [comment]
@ChaelKruip Maybe a different approach might help me:
How is the demand of `energy_regasification_lng` computed?

I cannot find a demand in [energy_regasification_lng.ad](https://github.com/quintel/etsource/blob/9e497c279596ab1f2157180b675e6e0759fdb95b/nodes/energy/energy_regasification_lng.ad). Nor in [energy_import_lng.ad](energy_import_lng.ad).

**Comment by ChaelKruip** [comment]
> I cannot find a demand in energy_regasification_lng.ad. Nor in energy_import_lng.ad.

I think it might be initialised through the gas-network (`energy_national_gas_network_natural_gas`) and the following share:

https://github.com/quintel/etsource/blob/master/datasets/be/shares/energy_national_gas_network_natural_gas_child_share.csv

You can look at the images which are created with the rake debug task to learn more.

**Comment by ploh** [comment]
> I think it might be initialised through the gas-network (energy_national_gas_network_natural_gas) and the following share

I would have thought so, too. But then it is very weird why the value is not scaled.

**Comment by ploh** [comment]
Do I have to scale the `central_producers.csv`? Or are these "per power plant / building / etc"?

**Comment by ploh** [comment]
And what about `primary_production.csv`?

**Comment by ploh** [comment]
And `metal_demands.csv`?

**Comment by ploh** [comment]
And `network/..._distribution.csv`?
btw: What do these do?

**Comment by antw** [comment]
> Do I have to scale the central_producers.csv? Or are these "per power plant / building / etc"?
> And what about primary_production.csv?
> And metal_demands.csv?

No, no, and no. The demands from these files are mapped to Refinery nodes; presumably these demands are already being scaled by your `GraphScaler`.

> And network/..._distribution.csv?
> btw: What do these do?

Also no. They determine the distribution of capacity in different networks – HV, MV, and LV – (see quintel/etengine#803) and should not need to be scaled.

**Comment by ploh** [comment]
> No, no, and no. The demands from these files are mapped to Refinery nodes; presumably these demands are already being scaled by your GraphScaler.

That sounds good :+1: 

But what else could I have missed? Some not-scaled value must be responsible for the unscaled lng demand.

**Comment by ploh** [comment]
> The demands from these files are mapped to Refinery nodes;

@antw Let us assume (since I ran out of other ideas) that some of these values will be re-used in etengine directly after being used by Refinery. Which are relative to the size of the dataset and therefore would have to be scaled?

**Comment by antw** [comment]
> Which are relative to the size of the dataset and therefore would have to be scaled?

I think the only ones are `demand`, `max_demand`, and `number_of_units` (although I would not *expect* any node to have this attribute, [one currently does](https://github.com/quintel/etsource/blob/9e497c279596ab1f2157180b675e6e0759fdb95b/nodes/transport/transport_car_using_electricity.converter.ad#L40-L42)). input or output capacity [should probably not be scaled](https://github.com/quintel/atlas/blob/c33304849e7f0aa3c3365532775a4cab47e62b42/lib/atlas/scaler/graph_scaler.rb#L9-L10).

It's curious that it only affects a handful of nodes; if it were an entire attribute not being scaled I would have thought the problem would be more widespread. If it is possible to reproduce this with the code already pushed, I will take a look tomorrow and see what I can find out.

**Comment by ploh** [comment]
> If it is possible to reproduce this with the code already pushed, I will take a look tomorrow and see what I can find out.

Yes, it is. Just checkout this branch in Atlas. Checkout the local-datasets branch in etsource and tell it to use your local atlas version. Checkout the local-datasets-loading-graph-yml branch in etengine and tell that also to use your local atlas. Checkout the local-datasets branch in etmodel.
Then in etsource execute
```
DATASET=nl LOCAL_DATASET=limburg NUMBER_OF_RESIDENCES=74493 rake scale
```
And finally fire up etengine and etmodel and create a new scenario for country "limburg".

**Comment by ploh** [comment]
> I think the only ones are demand, max_demand, and number_of_units

What I meant was: What of the above mentioned files do I have to scale? So, all columns in them which are of one of the three types?

**Comment by ploh** [comment]
> input or output capacity should probably not be scaled.

I had a discussion with @ChaelKruip in slack about this. It boiled down to this comment of his:
> These should not be scaled for any technologies but for the import nodes they should indeed! I never realised that these attributes where used there as well :S
> Actually, it is not very nice that this name is used for two slightly different things :disappointed:

They are set in these nodes in graph.yml:

```
  :energy_export_electricity:
    :typical_input_capacity: 58.500015706177955
    :in:
      :electricity: {}
    :out: {}
```
```
  :energy_import_electricity:
    :electricity_output_capacity: 58.500015706177955
    :in: {}
    :out:
      :imported_electricity: {}
```
```
  :energy_interconnector_imported_electricity:
    :max_demand: .inf
    :electricity_output_capacity: 58.500015706177955
    :in:
      :imported_electricity: {}
    :out:
      :electricity: {}
```

**Comment by ploh** [comment]
Unfortunately github forbids me to reopen this because the former base branch was deleted.
So I had to create a new PR for this: #77

**Comment by ChaelKruip** [comment]
> Also no. They determine the distribution of capacity in different networks – HV, MV, and LV – (see quintel/etengine#803) and should not need to be scaled.

@antw Why should they not be scaled? Derived datasets should not have the full country capacities right?

**Comment by ploh** [comment]
>>> And network/..._distribution.csv?

>> Also no.

> Why should they not be scaled? Derived datasets should not have the full country capacities right?

But the numbers in these files are percentages and thus not scalable, right?

**Comment by antw** [comment]
> @ChaelKruip But the numbers in these files are percentages and thus not scalable, right?

Correct.

To simplify, lets say you have a capacity distribution file with a single value: **0.8**. Your network has a peak load of **10000MW** and installed capacity of only **9000MW**.

[`required_additional_network_capacity_in_mw`](https://github.com/quintel/etengine/blob/8dc7746d293e9ca532f92cf5c8586e84e3c5f99e/app/models/qernel/converter_api/network.rb#L18-L51) = `(10_000 - 9_000) * 0.8 = 800MW`

If you scale the scenario down 100x:

[`required_additional_network_capacity_in_mw`](https://github.com/quintel/etengine/blob/8dc7746d293e9ca532f92cf5c8586e84e3c5f99e/app/models/qernel/converter_api/network.rb#L18-L51) = `(100 - 90) * 0.8 = 8MW`

**Pull request closed without merging**
